"""
Forum Agent - HackerNews, IndieHackers & ProductHunt Engagement.

Strategy:
- HackerNews: Comment on relevant posts about freelancing, payments, Web3.
  Post "Show HN" when product is ready.
- IndieHackers: Share building journey, help founders, engage in discussions.
- ProductHunt: Prepare and execute launch in Week 2.

All content generated by Claude. Uses HTTP requests (no official APIs).

Goal: 3-5 signups/week from forum engagement.
Rate limit: 15-20 thoughtful comments/week across all forums.
"""

import time
import requests
from datetime import datetime, date, timezone
from typing import List, Dict, Optional
from enum import Enum

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from base_agent import BaseAgent, RateLimitExceeded
from database import Platform, Conversation
from claude_client import TaskComplexity


# RepEscrow product context for Claude prompts
PRODUCT_CONTEXT = """
ABOUT REPESCROW:
RepEscrow is a reputation-weighted escrow platform on Solana.

Your FairScore (on-chain reputation from FairScale) determines your escrow fees:
- FairScore 4.5-5.0 → 0.5% fee, instant release
- FairScore 3.5-4.4 → 1.0% fee, 24hr hold
- FairScore 2.5-3.4 → 1.5% fee, 72hr hold
- FairScore 1.5-2.4 → 2.0% fee, 7-day hold
- FairScore <1.5    → 2.5% fee, 14-day hold

Upwork charges 20%. Traditional escrow charges flat 2-3%.
RepEscrow rewards reputation with lower fees. Built on Solana.

Website: repescrow.xyz
"""


class ForumPlatform(str, Enum):
    """Forum platforms we engage on."""
    HACKERNEWS = "hackernews"
    INDIEHACKERS = "indiehackers"
    PRODUCTHUNT = "producthunt"


# HackerNews search keywords for finding relevant stories
HN_SEARCH_KEYWORDS = [
    'escrow', 'freelance platform', 'upwork fees', 'fiverr',
    'web3 freelance', 'crypto payment', 'solana',
    'reputation system', 'trust online', 'scammed freelancer',
    'smart contract escrow', 'decentralized work',
    'gig economy', 'freelancer protection', 'payment dispute',
]


class ForumAgent(BaseAgent):
    """
    Engages on HackerNews, IndieHackers, and ProductHunt.

    Unlike Discord/Telegram (real-time monitoring), this agent runs
    on a schedule — the orchestrator calls run() once or twice a day.

    Daily workflow:
    1. Scrape HackerNews for relevant stories via Algolia API
    2. Generate thoughtful comments using Claude
    3. Queue comments for manual posting (or auto-post if HN account available)
    4. Log everything to Supabase for tracking

    Note: HN and IndieHackers don't have official posting APIs,
    so this agent generates content and stores it for manual posting
    or future Selenium automation.
    """

    MAX_COMMENTS_PER_DAY: int = 5
    MAX_HN_STORIES_TO_ANALYZE: int = 20

    def __init__(self) -> None:
        """Initialize Forum agent."""
        super().__init__(platform=Platform.FORUM)
        self._session = requests.Session()
        self._session.headers.update({
            'User-Agent': 'RepEscrow-ForumAgent/1.0'
        })

    def get_name(self) -> str:
        """Get agent name."""
        return "ForumAgent"

    def health_check(self) -> bool:
        """Forum agent is always healthy (uses HTTP, no auth needed)."""
        return True

    def run(self) -> None:
        """
        Execute daily forum engagement tasks.

        Called by orchestrator on schedule (typically 10am and 3pm).
        """
        self.logger.info(
            "forum_agent_run_started",
            date=str(date.today())
        )

        try:
            # Task 1: Find and comment on HackerNews stories
            hn_comments = self.safe_execute(self._engage_hackernews)
            self.logger.info("hn_engagement_completed", comments_generated=hn_comments or 0)

            # Task 2: Generate IndieHackers content
            ih_posts = self.safe_execute(self._engage_indiehackers)
            self.logger.info("ih_engagement_completed", posts_generated=ih_posts or 0)

            # Save metrics
            self.save_daily_metrics()

        except Exception as e:
            self.logger.error("forum_agent_run_failed", error=str(e))

    # -------------------------------------------------------------------------
    # HackerNews Engagement
    # -------------------------------------------------------------------------

    def _engage_hackernews(self) -> int:
        """
        Find relevant HN stories and generate thoughtful comments.

        Uses HN Algolia API (free, no auth) to search for relevant stories.
        Generates comments via Claude and stores them for posting.

        Returns:
            Number of comments generated
        """
        comments_generated = 0

        # Search for relevant stories
        stories = self._search_hn_stories()

        if not stories:
            self.logger.info("no_relevant_hn_stories_found")
            return 0

        for story in stories[:self.MAX_COMMENTS_PER_DAY]:
            try:
                self.enforce_rate_limit("comment", self.MAX_COMMENTS_PER_DAY)

                # Generate a thoughtful comment
                comment = self._generate_hn_comment(story)
                if not comment:
                    continue

                # Store the comment for posting
                self._store_generated_content(
                    forum=ForumPlatform.HACKERNEWS,
                    target_url=f"https://news.ycombinator.com/item?id={story['objectID']}",
                    target_title=story.get('title', ''),
                    content=comment
                )

                comments_generated += 1
                self.increment_action_count("comment")
                self.record_engagement()

                self.logger.info(
                    "hn_comment_generated",
                    story_title=story.get('title', '')[:60],
                    comment_length=len(comment)
                )

            except RateLimitExceeded:
                break
            except Exception as e:
                self.logger.error("hn_comment_failed", error=str(e))
                continue

        return comments_generated

    def _search_hn_stories(self) -> List[Dict]:
        """
        Search HackerNews via Algolia API for relevant stories.

        Returns recent stories (last 7 days) matching our keywords.
        """
        all_stories = []

        for keyword in HN_SEARCH_KEYWORDS[:5]:  # Limit to avoid rate limiting
            try:
                resp = self._session.get(
                    'https://hn.algolia.com/api/v1/search_by_date',
                    params={
                        'query': keyword,
                        'tags': 'story',
                        'numericFilters': 'created_at_i>=' + str(
                            int((datetime.now(timezone.utc).timestamp()) - 7 * 86400)
                        ),
                        'hitsPerPage': 5,
                    },
                    timeout=10
                )

                if resp.status_code == 200:
                    hits = resp.json().get('hits', [])
                    all_stories.extend(hits)

                time.sleep(1)  # Be nice to the API

            except Exception as e:
                self.logger.error("hn_search_failed", keyword=keyword, error=str(e))
                continue

        # Deduplicate by story ID
        seen = set()
        unique = []
        for story in all_stories:
            sid = story.get('objectID')
            if sid and sid not in seen:
                seen.add(sid)
                unique.append(story)

        # Sort by points (most popular first)
        unique.sort(key=lambda x: x.get('points', 0), reverse=True)

        self.logger.info("hn_stories_found", count=len(unique))
        return unique[:self.MAX_HN_STORIES_TO_ANALYZE]

    def _generate_hn_comment(self, story: Dict) -> Optional[str]:
        """Generate a thoughtful HN comment using Claude."""
        title = story.get('title', '')
        url = story.get('url', '')
        points = story.get('points', 0)

        prompt = f"""Write a HackerNews comment for this story.

STORY TITLE: {title}
STORY URL: {url}
POINTS: {points}

{PRODUCT_CONTEXT}

HN COMMENT RULES (critical — HN users are very smart and hate marketing):
1. Lead with genuine insight or personal experience
2. Add value to the discussion — share knowledge, data, or a unique perspective
3. NEVER start with "Great post!" or similar filler
4. Only mention RepEscrow if DIRECTLY relevant — and even then, frame it as
   "we're building X" or "I'm working on something similar" — NOT a pitch
5. If the story isn't about escrow/payments/freelancing, just add a helpful
   comment WITHOUT mentioning RepEscrow at all
6. Match HN tone: thoughtful, technical, slightly contrarian
7. Max 150 words
8. No emojis, no marketing speak, no exclamation marks
9. If you can share a relevant data point or statistic, do it
10. It's OK to disagree with the story — HN rewards nuanced takes

Return ONLY the comment text."""

        try:
            comment = self.claude.generate(
                prompt=prompt,
                complexity=TaskComplexity.COMPLEX,
                max_tokens=350,
                temperature=0.8
            )
            return comment.strip()

        except Exception as e:
            self.logger.error("hn_comment_generation_failed", error=str(e))
            return None

    # -------------------------------------------------------------------------
    # IndieHackers Engagement
    # -------------------------------------------------------------------------

    def _engage_indiehackers(self) -> int:
        """
        Generate IndieHackers-style content about the RepEscrow build journey.

        Since IH doesn't have a posting API, this generates content
        and stores it for manual posting.

        Returns:
            Number of posts generated
        """
        # Generate one building-in-public style post per day
        post = self._generate_ih_post()
        if not post:
            return 0

        self._store_generated_content(
            forum=ForumPlatform.INDIEHACKERS,
            target_url="https://www.indiehackers.com",
            target_title="Building in Public",
            content=post
        )

        self.increment_action_count("post")
        self.record_impression()

        self.logger.info("ih_post_generated", post_length=len(post))
        return 1

    def _generate_ih_post(self) -> Optional[str]:
        """Generate an IndieHackers building-in-public post."""
        prompt = f"""Write an IndieHackers "building in public" post about RepEscrow.

{PRODUCT_CONTEXT}

IH POST REQUIREMENTS:
1. Share a specific challenge, learning, or milestone from building RepEscrow
2. Be honest and transparent — IH loves authenticity
3. Include specific numbers if possible (users, revenue, metrics)
4. Ask a question to the community at the end (drives engagement)
5. 200-300 words
6. Tone: founder-to-founder, casual but insightful
7. Don't be salesy — share the JOURNEY, not the product
8. Topics to rotate between:
   - Technical challenges (Solana smart contracts, AI agents)
   - Traction strategies (what's working, what's not)
   - Market insights (Web3 freelance landscape)
   - Honest revenue/user numbers

Example opening lines:
- "Week 2 of building RepEscrow. Here's what I learned about..."
- "We hit 50 signups yesterday. But the interesting part is HOW..."
- "I almost gave up on our Solana integration. Here's why I didn't..."

Return ONLY the post text."""

        try:
            post = self.claude.generate(
                prompt=prompt,
                complexity=TaskComplexity.COMPLEX,
                max_tokens=600,
                temperature=0.9
            )
            return post.strip()

        except Exception as e:
            self.logger.error("ih_post_generation_failed", error=str(e))
            return None

    # -------------------------------------------------------------------------
    # Content Storage
    # -------------------------------------------------------------------------

    def _store_generated_content(
        self,
        forum: ForumPlatform,
        target_url: str,
        target_title: str,
        content: str
    ) -> None:
        """
        Store generated forum content in Supabase for manual posting.

        Saved to the 'forum_content' table (or conversations as fallback).
        """
        try:
            # Try dedicated forum_content table first
            self.db._client.table('forum_content').insert({
                'forum': forum.value,
                'target_url': target_url,
                'target_title': target_title,
                'content': content,
                'posted': False,
                'created_at': datetime.now(timezone.utc).isoformat(),
            }).execute()

            self.logger.info(
                "forum_content_stored",
                forum=forum.value,
                target_title=target_title[:50]
            )

        except Exception:
            # Fallback: store as a conversation with no prospect
            self.logger.warning("forum_content_table_missing_using_fallback")
            try:
                self.db._client.table('conversations').insert({
                    'prospect_id': 0,
                    'platform': 'forum',
                    'message': f"[{forum.value}] {target_title}\n{target_url}",
                    'response': content,
                    'timestamp': datetime.now(timezone.utc).isoformat(),
                }).execute()
            except Exception as e:
                self.logger.error("forum_content_storage_failed", error=str(e))
